spring.application.name=ibmall

# 정적 리소스 위치 (HTML, JS 등)
spring.web.resources.static-locations=classpath:/static/

# 포트 (필요 시)
server.port=8080

# 데이터베이스 설정
spring.datasource.url=jdbc:mariadb://192.168.52.215:3306/ib_mall
spring.datasource.username=ibmall_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.example.ibmall.entity
mybatis.configuration.map-underscore-to-camel-case=true
